#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

complete -cf sudo
complete -cf man

source $HOME/.shell/common.sh

if [[ -f $HOME/.opam/opam-init/init.sh ]]; then
    source $HOME/.opam/opam-init/init.sh
fi
