#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

complete -cf sudo
complete -cf man

source $HOME/.shell/common.sh

# opam for bash
if [[ -f $HOME/.opam/opam-init/init.sh ]]; then
    source $HOME/.opam/opam-init/init.sh
fi

# asdf completion for bash
if [[ -f "$HOME/.asdf/completions/asdf.bash" ]]; then
    . $HOME/.asdf/completions/asdf.bash
fi
