# Path to your oh-my-zsh installation.
ZSH=$HOME/.local/share/oh-my-zsh/

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git aws docker-compose fzf)

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ! -d $ZSH_CACHE_DIR ]]; then
    mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh

source $HOME/.shell/common.sh

# opam for bash
if [[ -f $HOME/.opam/opam-init/init.zsh ]]; then
    source $HOME/.opam/opam-init/init.zsh
fi

# asdf completion for zsh
# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit
compinit

# AWS completion
if [[ -e "$HOME/.local/bin/aws_completer" ]]; then
    complete -C $HOME/.local/bin/aws_completer aws
fi

# base prompt
export PROMPT="%{$fg_bold[yellow]%}${AWS_VAULT}${AWS_VAULT:+ }%{$fg_bold[blue]%}${HOST} %{$fg_bold[green]%}[%D{%H:%M:%S}] $PROMPT"

# kube-ps1
if [[ -e "$HOME/.shell/kube-ps1/kube-ps1.sh" ]]; then
    source $HOME/.shell/kube-ps1/kube-ps1.sh
    export KUBE_PS1_NS_ENABLE=false
    export KUBE_PS1_SYMBOL_ENABLE=false
    export KUBE_PS1_CTX_COLOR=blue
    export PROMPT='$(kube_ps1)'$PROMPT
fi

# kubectl completion
if kubectl &> /dev/null; then
    source <(kubectl completion zsh)
else
    if command -v kubeoff &> /dev/null; then
        kubeoff
    fi
fi

# k3d completion
if k3d &> /dev/null; then
    source <(k3d completion zsh)
fi
