#!/usr/bin/env bash

latex_templates_dir=$HOME/.local/share/latex-templates

if [[ $# -ne 2 ]]; then
    echo "$0 report|slide NAME"
    exit 1
fi

if ! [[ -e $latex_templates_dir ]]; then
    echo "latex lamplates not found at $latex_templates_dir"
    exit 1
fi

set -e
target_dir="$(pwd)/$2"
mkdir $target_dir
cp "$latex_templates_dir/$1.tex" "$target_dir/main.tex"
cp "$latex_templates_dir/Makefile" $target_dir
cp "$latex_templates_dir/mystylefile.sty" $target_dir
