if has("unix")
    let s:uname_s = substitute(system("uname -s"), '\n', '', '')
    if s:uname_s == "Darwin"
        set guifont=Ricty\ Regular:h16
    elseif s:uname_s == "Linux"
        set guifont=Ricty\ Regular\ 13
    endif
endif
set visualbell t_vb=
