[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_color_term = 63
    let g:indent_guides_start_level = 2
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
    hi Visual ctermbg=231
    hi MatchParen ctermbg=darkblue
    colorscheme iceberg
'''

[[plugins]]
repo = 'shiracamus/vim-syntax-x86-objdump-d'

[[plugins]]
repo = 'cespare/vim-toml'
