set t_Co=256
set number
syntax on
set tabstop=4
set expandtab
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent
set cursorline
set laststatus=2 
set statusline=%F\ %r%m%h%w%=%y\ [%04l/%04L,\ %04v]
set cino=N-s
set backspace=indent,eol,start

"if vim slow 
"set lazyredraw
"set ttyfast

" dein settings {{{
if &compatible
  set nocompatible
endif

let s:vim_dir = expand('~/.vim')
let s:dein_dir = s:vim_dir . '/dein'
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if !isdirectory(s:dein_repo_dir)
  execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
endif

execute 'set runtimepath^=' . s:dein_repo_dir

if dein#load_state(s:dein_dir)
    call dein#begin(s:dein_dir)

    let s:toml = s:vim_dir . '/plugins.toml'
    let s:lazy_toml = s:vim_dir . '/plugins_lazy.toml'
    call dein#load_toml(s:toml, {'lazy': 0})
    call dein#load_toml(s:lazy_toml, {'lazy': 1})

    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
endif
filetype plugin indent on
" }}}

" yapf
map <C-Y><C-F> :call yapf#YAPF()<cr>
imap <C-Y><C-F> <c-o>:call yapf#YAPF()<cr>
