[theme]
name="gruvbox-dark"
[theme.overrides]
#idle_bg = "#ffffff"
idle_fg = "#ffffff"
#info_bg = "#ffffff"
info_fg = "#ffffff"
#good_bg = "#ffffff"
good_fg = "#ffffff"
#warning_bg = "#ffffff"
warning_fg = "#ffffff"
#critical_bg = "#ffffff"
critical_fg = "#ffffff"
#separator_bg = "#ffffff"
#separator_fg = "#ffffff"
#alternating_tint_bg = "#ffffff"
alternating_tint_fg = "#ffffff"

[icons]
name = "awesome"
[icons.overrides]
time = " "

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false

[[block]]
block = "net"
device = "wlp3s0"
ip = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "battery"
interval = 10

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%Y-%m-%d(%a) %H:%M:%S"
