#!/usr/bin/env python3

import argparse
import subprocess

LIST, START = ('list', 'start')
V_BOX_MANAGE = 'VBoxManage'


def do_list(_):
    result = subprocess.run([V_BOX_MANAGE, 'list', 'vms'], stdout=subprocess.PIPE)
    print(result.stdout.decode().strip())


def do_start(args):
    command = [V_BOX_MANAGE, 'startvm', args.target, '--type']
    if args.with_gui:
        command.append('gui')
    else:
        command.append('headless')
    subprocess.run(command)


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='command')
    subparsers.required = True
    parser_list = subparsers.add_parser(LIST)
    parser_list.set_defaults(func=do_list)
    parser_start = subparsers.add_parser(START)
    parser_start.add_argument('target')
    parser_start.add_argument('-g', '--with-gui', action='store_true')
    parser_start.set_defaults(func=do_start)
    args = parser.parse_args()
    args.func(args)


if __name__ == '__main__':
    main()
